logging:
  level:
    root: info
    com.g.fot: debug
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug
#  file:
#    path: logs/
#    name: logs/app.log

spring:
  datasource:
    url: jdbc:ch://47.94.96.234:18123
    username: root
    password: P7HtW800kgmx
    name: ClickHouse
    type: com.clickhouse.jdbc.ClickHouseDataSource

